[env]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder
lib_deps = adafruit/Adafruit NeoPixel

[env:esp8266_master]
extends = env
src_filter = +<master.cpp>

[env:esp8266_slave]
extends = env
src_filter = +<slave.cpp>



; pio run -t upload -e esp8266_slave1 ; pio run -t upload -e esp8266_slave2 ; pio run -t upload -e esp8266_master;

; pio run -t upload -e esp8266_master; pio run -t upload -e esp8266_slave