<#
.SYNOPSIS
  Generate git-ignored pairing.h files for a controller + box(es) set by reading
  each board's MAC over USB. One command per new hardware setup.

.DESCRIPTION
  Reads the STA MAC of each board with esptool, derives the controller's SoftAP
  MAC (STA + 1 in the last octet — the ESP32 default), and writes:
    controller/main/pairing.h     PAIR_BOX0_MAC [, PAIR_BOX1_MAC]
    firmware/main/pairing.h       PAIR_CONTROLLER_MAC
    cyd-dashboard/main/pairing.h  PAIR_CONTROLLER_MAC
  These files are git-ignored; the committed defaults are never touched.

  NOTE: the SoftAP MAC is derived, not measured. After flashing the controller,
  confirm its boot log line ("controller booted: AP ... MAC <x>") matches the
  PAIR_CONTROLLER_MAC written here; re-run with -ApMac if it differs.

.EXAMPLE
  pwsh scripts/gen-pairing.ps1 -ControllerPort COM4 -Box0Port COM5
#>
param(
  [Parameter(Mandatory = $true)][string]$ControllerPort,
  [Parameter(Mandatory = $true)][string]$Box0Port,
  [string]$Box1Port,
  [string]$ApMac,                                   # override the derived SoftAP MAC, e.g. "a4:f0:0f:61:66:45"
  [string]$IdfExport = "C:\esp\v6.0.1\esp-idf\export.ps1"
)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot   # repo root (scripts/ is one level down)

if (Test-Path $IdfExport) { & $IdfExport | Out-Null }
$env:ESPTOOL_CUSTOM_RESET_SEQUENCE = "D0|R1|W0.6|D1|R0|W0.4|D0"

function Read-StaMac([string]$port) {
  $out = python -m esptool --chip esp32 -p $port --before default-reset --connect-attempts 2 read-mac 2>&1 | Out-String
  $m = [regex]::Match($out, 'MAC:\s*([0-9a-fA-F:]{17})')
  if (-not $m.Success) { throw "Could not read MAC on $port. esptool said:`n$out" }
  return $m.Groups[1].Value.ToLower()
}
function To-Braces([string]$mac) { ($mac -split ':' | ForEach-Object { "0x$_" }) -join ', ' }
function Derive-ApMac([string]$staMac) {
  $b = @($staMac -split ':' | ForEach-Object { [Convert]::ToInt32($_, 16) })
  $b[5] = ($b[5] + 1) -band 0xFF
  ($b | ForEach-Object { '{0:x2}' -f $_ }) -join ':'
}

$ctrlSta = Read-StaMac $ControllerPort
$box0    = Read-StaMac $Box0Port
$box1    = if ($Box1Port) { Read-StaMac $Box1Port } else { $null }
$ctrlAp  = if ($ApMac) { $ApMac.ToLower() } else { Derive-ApMac $ctrlSta }

Write-Host "Controller $ControllerPort  STA=$ctrlSta  ->  SoftAP=$ctrlAp" -ForegroundColor Cyan
Write-Host "Box 0      $Box0Port  STA=$box0" -ForegroundColor Cyan
if ($box1) { Write-Host "Box 1      $Box1Port  STA=$box1" -ForegroundColor Cyan }

$stamp = "generated by gen-pairing.ps1 — git-ignored, NOT committed."

$ctrlContent = "#pragma once`n// $stamp`n#define PAIR_BOX0_MAC { $(To-Braces $box0) }`n"
if ($box1) { $ctrlContent += "#define PAIR_BOX1_MAC { $(To-Braces $box1) }`n" }
$apContent = "#pragma once`n// $stamp`n// Controller SoftAP MAC (verify against controller boot log).`n#define PAIR_CONTROLLER_MAC { $(To-Braces $ctrlAp) }`n"

Set-Content -Path (Join-Path $root 'controller/main/pairing.h')     -Value $ctrlContent -Encoding utf8 -NoNewline
Set-Content -Path (Join-Path $root 'firmware/main/pairing.h')       -Value $apContent   -Encoding utf8 -NoNewline
Set-Content -Path (Join-Path $root 'cyd-dashboard/main/pairing.h')  -Value $apContent   -Encoding utf8 -NoNewline

Write-Host "`nWrote controller/main/pairing.h, firmware/main/pairing.h, cyd-dashboard/main/pairing.h" -ForegroundColor Green
Write-Host "Now rebuild + flash all three. Confirm the controller boot-log MAC == $ctrlAp (else re-run with -ApMac)." -ForegroundColor Yellow
